apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: klline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: image-registry.openshift-image-registry.svc:5000/klline/klline-frontend:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 8080
          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
