apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: klline

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - backend.yaml
  - celery.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: klline
  app.kubernetes.io/managed-by: kustomize
